# Site Settings
title: Mio Ebisu
email: contact@mioebisu.com
description: >
  The website of Mio Ebisu.
baseurl: ""
url: "http://localhost:4000"
sass:
  sass_dir: _sass
include: ['_pages']
collections:
  paintings:
    output: true
  drawings:
    output: true
  exhibitions:
    output: true
defaults:
  - scope:
      path: ""
      type: paintings
    values:
      layout: single
  - scope:
      path: ""
      type: drawings
    values:
      layout: single
  - scope:
      path: ""
      type: exhibitions
    values:
      layout: single